services:
  prod:
    build:
      context: ./docker/
      dockerfile: Dockerfile.prod
    image: mizucopo/rtsp2storage:latest
    platform: linux/amd64
  dev:
    build:
      context: ./docker/
      dockerfile: Dockerfile.dev
    image: mizucopo/rtsp2storage:develop
    platform: linux/amd64
