---
name: Build and Push Docker image

"on":
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: 読み込んだバージョンを取得
        id: vars
        run: echo "version=$(cat VERSION)" >> "$GITHUB_OUTPUT"

      - name: リポジトリ名を取得
        id: repo
        run: |
          repo=$(basename "$GITHUB_REPOSITORY")
          echo "repo=$repo" >> "$GITHUB_OUTPUT"
          echo "image=mizucopo/$repo" >> "$GITHUB_OUTPUT"

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: ./docker
          file: ./docker/Dockerfile.prod
          platforms: linux/amd64
          push: true
          tags: |
            ${{ steps.repo.outputs.image }}:latest
            ${{ steps.repo.outputs.image }}:${{ steps.vars.outputs.version }}

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.vars.outputs.version }}
          target_commitish: main
          name: Release ${{ steps.vars.outputs.version }}
          body: |
            VERSION: ${{ steps.vars.outputs.version }}
            Docker image:
              ${{ steps.repo.outputs.image }}:${{ steps.vars.outputs.version }}
